name: AutoReleaseJar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Cache .gradle/wrapper
      uses: actions/cache@v3
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-wrapper-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SakuraBind Artifact
        path: build/*.jar
